### ISSUE TITLE
Failed to connect successfully error

### ISSUE THREAD

**Issue by WeebNetsu** [mearaj/nordlayer#4]
I have logged in successfully, but I cannot connect to any Gateway
![Selection_148](https://user-images.githubusercontent.com/52031254/177712869-86fcfe1a-0f9a-4c4f-816a-ea9b1abbd235.png)

I've also tried `usermod -a -G nordlayer $(whoami)`, but didn't change anything

**Comment by mearaj** [comment]
Hi @WeebNetsu ,
Thanks for opening the issue.
Actually this issue is not related to this repo.
This repo is only meant to create a compatible package of nordlayer on Arch Linux.
I have tested it on my OS and it's working fine.
Your issue seems to be related to nordlayer itself.
Please let nordlayer people know your issue.
You can try few troubleshooting steps like logout/relogin or disconnect/connect or uninstall/install or restarting your pc? or
it may be [dns issue](https://help.nordlayer.com/hc/en-us/articles/4404768674065-How-to-change-DNS-on-Linux-)
You can also try searching here [nordlayer linux](https://help.nordlayer.com/hc/en-us/search?utf8=%E2%9C%93&query=linux)

If your issue gets resolved, then please let us know, so it can help others and issue can be closed.
Thanks :)

**Comment by WeebNetsu** [comment]
Hello! Thank you for your reply! I did get it working in the end, I just spammed "nordlayer c mygate" and surprisingly enough after a few attempts it started working! I have to do this each time I want to connect, but for now it works... I'll get in touch with their support and also hear what they have to say about it

**Comment by mearaj** [comment]
Hi @all, 
The previous issues should be resolved [now](https://github.com/mearaj/nordlayer/commit/5662a38ed243f5eeb4cd05a2eeb6b3c379449f5d). 
(Upgraded to new version and found a bug previous nordlayer.install file). Please do let me know if any issues. Thanks :)
